version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
      - "8888:8888"
    volumes:
      - ./app:/app
    command: >
      sh -c "cd app/ && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=varsvid
      - DB_USER=varsvid
      - DB_PASSWORD=varsvid
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: postgres:12.2
    environment:
      - POSTGRES_DB=varsvid
      - POSTGRES_PASSWORD=varsvid
      - POSTGRES_USER=varsvid
    ports:
      - "5432"
