# Generated by Django 3.0.7 on 2020-06-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='location',
            new_name='to_location',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='to_name',
        ),
        migrations.AddField(
            model_name='destination',
            name='from_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='from_name',
            field=models.CharField(default='Current location', max_length=255),
            preserve_default=False,
        ),
    ]
