# Generated by Django 3.0.7 on 2020-06-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_auto_20200614_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='from_latitude',
            field=models.DecimalField(decimal_places=6, default=51.9253, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='from_longitude',
            field=models.DecimalField(decimal_places=6, default=14.235, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='to_latitude',
            field=models.DecimalField(decimal_places=6, default=51.9253, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='to_longitude',
            field=models.DecimalField(decimal_places=6, default=14.235, max_digits=9),
            preserve_default=False,
        ),
    ]
