# Generated by Django 3.0.7 on 2020-06-15 02:26

from django.db import migrations
# Generated by Django 3.0.7 on 2020-06-15 02:01

from django.db import migrations

destinations = [
    {
        'data': {
            'to_name': 'Araraquara',
            'to_location': 'Rua Teste, 65',
            'to_latitude': 21.7848,
            'to_longitude': 48.1786,
            'from_name': 'Rod. dos Bandeirantes, s/n - KM 34 - Calcário, Caieiras - SP, 07700-000',
            'from_location': 'Frango Assado',
            'from_latitude': -23.117731,
            'from_longitude': -46.989539,
            'is_favorite': True,
        },
    },
    {
        'data': {
            'to_name': 'Hopi Hari',
            'to_location': 'Rua Teste, 65',
            'to_latitude': 23.0977,
            'to_longitude': 47.0086,
            'from_name': 'Rod. dos Bandeirantes, km 72 - Moinho, Vinhedo - SP',
            'from_location': 'Frango Assado',
            'from_latitude': -23.117731,
            'from_longitude': -46.989539,
            'is_favorite': False,
        },
    },
    {
        'data': {
            'to_name': 'Hopi Hari',
            'to_location': 'Rua Teste, 65',
            'to_latitude': 4.5258,
            'to_longitude': 37.7056,
            'from_name': 'Avenida da Praia',
            'from_location': 'Frango Assado',
            'from_latitude': -23.117731,
            'from_longitude': -46.989539,
            'is_favorite': True,
        },
    },
]


def create_destinations(apps, schema_editor):
    Destination = apps.get_model('destinations', 'Destination')
    User = apps.get_model('user', 'User')
    user = User.objects.get(id=1)
    for destinations_to_create in destinations:
        destinations_to_create['data']['user'] = user
        Destination.objects.create(**destinations_to_create['data'])


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_auto_20200615_0133'),
    ]

    operations = [
        migrations.RunPython(create_destinations)
    ]
