# Generated by Django 3.0.7 on 2020-06-15 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_auto_20200615_0133'),
    ]

    operations = [
    ]
