# Generated by Django 3.0.7 on 2020-06-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.SmallIntegerField(choices=[(1, 'ONE STAR'), (2, 'TWO STARS'), (3, 'THREE STARS'), (4, 'FOUR STARS'), (5, 'FIVE STARS')])),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
