# Generated by Django 3.0.7 on 2020-06-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.SmallIntegerField(choices=[(1, 'health'), (2, 'hygiene'), (3, 'food'), (4, 'rest'), (5, 'safety')])),
            ],
        ),
    ]
