# Generated by Django 3.0.7 on 2020-06-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='services',
            field=models.ManyToManyField(to='places.Service'),
        ),
    ]
