# Generated by Django 3.0.7 on 2020-06-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20200614_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
