# Generated by Django 3.0.7 on 2020-06-14 22:50

from django.db import migrations

places = [
    {
        'data': {
            'name': 'Frango Assado',
            'latitude': -23.350396,
            'longitude': -46.797085,
            'rating': 3,
            'address': 'Rod. dos Bandeirantes, s/n - KM 34 - Calcário, Caieiras - SP, 07700-000'
        },
        'services': [3]
    },
    {
        'data': {
            'name': 'Posto CCR Campeão',
            'latitude': -23.117731,
            'longitude': -46.989539,
            'rating': 5,
            'address': 'Rodovia dos Bandeirantes, Km 68,5 s/n - Jardim Ermida II, SP, 13212-195'
        },
        'services': [2, 3, 4]
    },
    {
        'data': {
            'name': 'Polícia Rodoviária Federal',
            'latitude': -22.871536,
            'longitude': -45.288596,
            'rating': 2,
            'address': '3192, Rod. Pres. Dutra, 1804, Roseira - SP, 12580-000'
        },
        'services': [5]
    },
{
        'data': {
            'name': 'Hospital São Camilo - Unidade Pompeia (Internação)',
            'latitude': -23.532878,
            'longitude': -46.688901,
            'rating': 4,
            'address': 'R. Barão do Bananal, 1111 - Pompeia, São Paulo - SP, 05024-000'
        },
        'services': [1]
    }
]


def create_places(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    Service = apps.get_model('places', 'Service')
    for place_to_create in places:
        place = Place.objects.create(**place_to_create['data'])
        place_services = Service.objects.filter(service_type__in=place_to_create['services'])
        place.services.add(*place_services)


class Migration(migrations.Migration):
    dependencies = [
        ('places', '0005_auto_20200614_2249'),
    ]

    operations = [
        migrations.RunPython(create_places)
    ]
